import type {
  IAviaOrderFlight,
  IAviaOrderPassenger,
} from "@/modules/Orders/Avia/types";

export interface ICards {
  code: number;
  message: "success";
  data: {
    id: number;
    user_id: number;
    title: string;
    number: string;
    month: string;
    year: string;
    cvv: null;
    created_at: number;
    updated_at: number;
    created_by: number;
    updated_by: number;
    type: string;
  };
}

interface ISeatData {
  book_id: number;
  colspan: number;
  rowspan: string;
}
export interface IOrder {
  id: 90807;
  user_id: 12;
  agent_id: null;
  sub_agent_id: null;
  status: 4;
  status_pay: 0;
  price: 15;
  skit_for_agent: null;
  tariff_price: 0;
  currency: "USD";
  all_pax: null;
  class: null;
  debt: null;
  email: "shaxboz.p@asialuxe.uz";
  phone: "+998 90 729 11 29";
  full_name: "Shaxboz Pulatov";
  created_at: 1713003459;
  updated_at: 1713004382;
  created_by: 12;
  updated_by: 666;
  product_id: 5;
  provider_id: 1;
  provider_order_id: null;
  provider_order_status: null;
  payment_provider: null;
  price_usd: 15;
  price_uzs: 15;
  agent_fare: 15;
  comment: null;
  seat_data: ISeatData[];
  directions: [];
  flight: IAviaOrderFlight;
}
export interface ITourOrderSeats {
  id: number;
  user_id: number;
  agent_id: null;
  sub_agent_id: null;
  status: number;
  status_pay: number;
  price: number;
  skit_for_agent: null;
  tariff_price: number;
  currency: string;
  all_pax: number;
  class: string;
  debt: null;
  email: string;
  phone: string;
  full_name: string;
  created_at: number;
  updated_at: number;
  created_by: number;
  updated_by: number;
  product_id: number;
  provider_id: number;
  provider_order_id: null;
  provider_order_status: null;
  payment_provider: null;
  price_usd: number;
  comment: string;
  parent_id: null;
  seat_data: null;
  passengers: IAviaOrderPassenger[];
  directions: {
    id: number;
    tariff_price: null;
    currency: null;
    flight: {
      id: number;
      departure_code: string;
      departure_date: number;
      departure_date_format: string;
      departure_terminal: null;
      departure_time: number;
      departure_time_format: string;
      arrival_code: string;
      arrival_date: number;
      arrival_date_format: string;
      arrival_terminal: null;
      arrival_time: number;
      arrival_time_format: string;
      flight: string;
      flight_number: string;
      flight_unique_code: null;
      baggage_y: string;
      baggage_c: string;
      active_quota_y: number;
      active_quota_c: number;
      handbag: string;
      status: number;
      plane: string;
      airline_logo: null;
      airline_name: string;
      block_count: null;
      block_class: null;
      block_price: null;
      block_type: null;
      comment: null;
    };
    tariff: null;
  }[];
}
export interface ITransferItem {
  id: number;
  title: string;
  car_models: string;
  car_photo: string;
  car_capacity: number;
  class_services: string;
  additional_services: string;
  distance: string;
  travel_time: number;
  start_time_zone_code: string;
  start_address: string;
  start_point: string;
  start_time: string;
  finish_address: string;
  finish_point: string;
  finish_time: string;
  flexible_tariff: number;
  large_order_id: number;
  start_number: string;
  flexible_tariff_agreement: number;
  meeting_with_table: string;
}

export interface ITransferOrder {
  code: number;
  message: string;
  data: {
    id: number;
    agent_id: number;
    user_id: number;
    sub_agent_id: null;
    manager_id: null;
    office_id: null;
    parent_id: null;
    flight_order_id: null;
    product_id: number;
    status: number;
    visa_status: null;
    insurance_status: null;
    transfer_status: number;
    status_pay: number;
    price: number;
    tariff_price: number;
    netto_price: number;
    payment_advance: null;
    skit_for_agent: null;
    currency: string;
    usd_price: number;
    all_pax: number;
    provider_order_status: number;
    payment_provider: number;
    payment_provider_order_status: null;
    payment_expire: null;
    provider: string;
    class: null;
    email: string;
    phone: string;
    full_name: string;
    expire: null;
    checkin: string;
    checkout: string;
    route: string;
    main_region: string;
    sub_region: null;
    hotel_name: null;
    comment: null;
    vaucher_status: null;
    deleted_at: null;
    deleted_id: null;
    created_at: string;
    updated_at: null;
    created_by: number;
    updated_by: number;
    month: null;
    year: null;
    base: null;
    provider_order_pay_date: null;
    ex_id: null;
    adt: null;
    chi: null;
    inf: null;
    platform: null;
    price_usd: number;
    ex_amount: null;
    ex_currency: null;
    price_data: null;
    sales_mod: null;
    ip: string;
    child_ages: null;
    org_id: number;
    discount: null;
    old_price_discount: null;
    penalty: null;
    penalty_comment: null;
    penalty_log: null;
    penalty_date: null;
    no_bonus: null;
    combine_tour_id: null;
    discount_type: null;
    discount_value: null;
    discount_percent: null;
    no_bonus_agent: null;
    no_bonus_agent_comment: null;
    device: null;
    is_web_view: null;
    promo_code: null;
    promo_discount: null;
    provider_order_id: number;
    provider_transaction_id: number;
    transfer: ITransferItem[];
  };
}
